# This rule is not used by the project datarestor-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to backup.datarestor-operator.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: datarestor-operator
    app.kubernetes.io/managed-by: kustomize
  name: config-viewer-role
rules:
  - apiGroups:
      - backup.datarestor-operator.com
    resources:
      - configs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - backup.datarestor-operator.com
    resources:
      - configs/status
    verbs:
      - get
