# This rule is not used by the project cheap-man-ha-store itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to storage.cheap-man-ha-store.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cheap-man-ha-store
    app.kubernetes.io/managed-by: kustomize
  name: pvcbackup-viewer-role
rules:
- apiGroups:
  - storage.cheap-man-ha-store.com
  resources:
  - pvcbackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.cheap-man-ha-store.com
  resources:
  - pvcbackups/status
  verbs:
  - get
