---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backup.datarestor-operator.com
  resources:
  - backupconfigs
  - resticbackups
  - resticrepositories
  - resticrestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backup.datarestor-operator.com
  resources:
  - backupconfigs/finalizers
  - resticbackups/finalizers
  - resticrepositories/finalizers
  - resticrestores/finalizers
  verbs:
  - update
- apiGroups:
  - backup.datarestor-operator.com
  resources:
  - backupconfigs/status
  - resticbackups/status
  - resticrepositories/status
  - resticrestores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
