apiVersion: backup.datarestor-operator.com/v1alpha1
kind: BackupConfig
metadata:
  name: backupconfig-restic-example
  namespace: default
spec:
  # Auto-restore for new PVCs
  autoRestore: true

  # Backup targets using Restic
  backupTargets:
    # S3-compatible storage via Restic
    - name: s3-backup
      priority: 1
      restic:
        repository: "s3:s3.amazonaws.com/my-backup-bucket"
        env:
          - name: RESTIC_PASSWORD
            value: "your-encryption-password"
          - name: AWS_ACCESS_KEY_ID
            value: "minio-access-key"
          - name: AWS_SECRET_ACCESS_KEY
            value: "minio-secret-key"
          - name: AWS_DEFAULT_REGION
            value: "eu-central-1"
        tags:
          - "production"
          - "daily-backup"
        host: "k8s-cluster-1"
        flags:
          - "--verbose"
          - "--compression=auto"
        image: "restic/restic:latest"
      retention:
        maxSnapshots: 30
        maxAge: "2160h"

  # PVC selection criteria
  selectors:
    - stopPods: true
      labelSelector:
        matchLabels:
          app: database
          backup: "true"
      namespaces:
        - "production"
        - "staging"
      names:
        - "postgres-data"
        - "mysql-data"
