apiVersion: storage.cheap-man-ha-store.com/v1alpha1
kind: PVCBackup
metadata:
  labels:
    app.kubernetes.io/name: cheap-man-ha-store
    app.kubernetes.io/managed-by: kustomize
  name: pvcbackup-sample
spec:
  # TODO(user): Add fields here
