apiVersion: storage.cheap-man-ha-store.com/v1alpha1
kind: PVCBackup
metadata:
  name: pvcbackup-restic-example
  namespace: default
spec:
  # Backup targets using Restic
  backupTargets:
    # S3-compatible storage via Restic
    - name: s3-backup
      priority: 1
      restic:
        repository: "s3:s3.amazonaws.com/my-backup-bucket"
        password: "your-encryption-password"
        env:
          - name: AWS_ACCESS_KEY_ID
            value: "your-access-key"
          - name: AWS_SECRET_ACCESS_KEY
            value: "your-secret-key"
          - name: AWS_DEFAULT_REGION
            value: "us-west-2"
        tags:
          - "production"
          - "daily-backup"
        host: "k8s-cluster-1"
        flags:
          - "--verbose"
          - "--compression=auto"

    # NFS storage via Restic
    - name: nfs-backup
      priority: 2
      restic:
        repository: "local:/mnt/backup/restic-repo"
        password: "your-encryption-password"
        tags:
          - "local-backup"
          - "redundant"
        host: "k8s-cluster-1"
        flags:
          - "--no-lock"
      nfs:
        server: "nfs.example.com"
        path: "/backup"
        mountOptions: ["nfsvers=4", "soft"]
        mountPath: "/mnt/backup"

  # PVC selection criteria
  pvcSelector:
    labelSelector:
      matchLabels:
        app: database
        backup: "true"
    namespaces:
      - "production"
      - "staging"
    names:
      - "postgres-data"
      - "mysql-data"

  # Backup schedule
  schedule:
    cron: "0 2 * * *" # Daily at 2 AM
    waitForHealthy: true
    stopPods: false

  # Auto-restore for new PVCs
  autoRestore: true

  # Retention policy (applied to all targets)
  retention:
    maxSnapshots: 30
    maxAge: "90d"

  # Init container for restore waiting
  initContainer:
    image: "busybox:1.35"
    command: ["/bin/sh"]
    args: ["-c", "echo 'Waiting for restore to complete...' && sleep 10"]
