apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "datarestor-operator.fullname" . }}-manager-role
  labels:
  {{- include "datarestor-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backup.datarestor-operator.com
  resources:
  - configs
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backup.datarestor-operator.com
  resources:
  - configs/finalizers
  - tasks/finalizers
  verbs:
  - update
- apiGroups:
  - backup.datarestor-operator.com
  resources:
  - configs/status
  - tasks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - backup.datarestor-operator.com
  resources:
  - tasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "datarestor-operator.fullname" . }}-manager-rolebinding
  labels:
  {{- include "datarestor-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "datarestor-operator.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "datarestor-operator.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'